const root=document.querySelector('main');
const citation=document.getElementById('citation'),evidence=document.getElementById('citation-card'),source=document.getElementById('source-panel'),hint=document.getElementById('interaction-hint');
function setStep(step,focus=false){
 if(step==='evidence'){const stage=document.querySelector('.evidence-stage').getBoundingClientRect(),chip=citation.getBoundingClientRect();evidence.style.top=(chip.bottom-stage.top+14)+'px'}
 evidence.hidden=step!=='evidence';source.hidden=step!=='source';citation.setAttribute('aria-expanded',String(step!=='answer'));
 document.querySelectorAll('[data-step]').forEach(b=>{const active=b.dataset.step===step;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
 hint.textContent=step==='answer'?'Hover or focus on [2] to inspect the citation. Click it to open the source.':step==='evidence'?'Citation 2 identifies the supporting textbook and source pages.':'The source passage is open. Compare its support with the original claim.';
 if(focus&&step==='source')document.getElementById('close-source').focus();
}
citation.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&source.hidden)setStep('evidence')});
citation.addEventListener('focus',()=>{if(source.hidden)setStep('evidence')});
citation.addEventListener('click',()=>setStep('source',true));
document.getElementById('open-source').addEventListener('click',()=>setStep('source',true));
document.getElementById('close-source').addEventListener('click',()=>{setStep('answer');citation.focus();setStep('answer')});
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>setStep(b.dataset.step,b.dataset.step==='source')));
document.querySelector('.evidence-stage').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();setStep('answer');citation.focus();setStep('answer')}});
const modal=document.getElementById('evidence-modal'),shot=document.getElementById('evidence-image'),shotInfo=document.getElementById('evidence-description'),original=document.getElementById('original-link');
const images={S02:['Automotive knowledge graph','Original product capture: connected automotive industry knowledge domains. The main-page network is a conceptual product representation.'],'S01-full':['Teacher workspace','Original product capture: integrated teacher workspace with product navigation, professional Q&A, lesson generation and learning diagnosis entry points.'],S11:['Question analysis','Original product capture: question, explanation and response distribution.'],S12:['Knowledge-point performance','Original product capture: fatigue strength 49%, machine characteristics 55.1%, deformable solids 55.1%.'],S13:['AI teaching recommendations','Original product capture: suggested review, practice and teaching adjustments. The main-page recommendation is an illustrative response, not a translation of this output.'],S03:['Answer with citation 2','Original product capture: question, answer and inline reference.'],S04:['Citation 2 hover card','Original product capture: textbook title and cited pages.'],S05:['Original source panel','Original product capture: source title and retrieved passages.'],S07:['Teaching context','Original product capture: EV power battery systems, thermal runaway chapter and two lesson periods.'],S08:['Generation process','Original product capture: curriculum, teaching materials, template and industry knowledge retrieval during generation.'],S09:['AI refinement workspace','Original product capture: the lesson artefact and assistant share a workspace.'],'S09-detail':['AI refinement detail','Original product capture: the assistant confirms that the requested addition has been applied to the lesson.'],S10:['Manual editing','Original product capture: precise slide editing with page thumbnails and an editable canvas.']};
function showImage(key){shot.src='assets/'+key+'.png';shot.alt=images[key][0];shotInfo.textContent=images[key][1];original.href=shot.src;document.querySelectorAll('[data-shot]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.shot===key)))}
function openEvidence(key='S03',keys=['S03','S04','S05']){const tabs=document.querySelector('.evidence-tabs');tabs.replaceChildren();keys.filter(k=>images[k]).forEach(k=>{const b=document.createElement('button');b.type='button';b.dataset.shot=k;b.textContent=k+' / '+images[k][0];b.setAttribute('aria-pressed',String(k===key));tabs.append(b)});showImage(key);modal.showModal();document.body.classList.add('modal-open')}
document.getElementById('open-evidence').addEventListener('click',()=>openEvidence());document.getElementById('source-evidence').addEventListener('click',()=>openEvidence('S05'));
document.getElementById('close-evidence').addEventListener('click',()=>modal.close());modal.addEventListener('close',()=>document.body.classList.remove('modal-open'));modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()}});
document.querySelector('.evidence-tabs').addEventListener('click',e=>{const button=e.target.closest('[data-shot]');if(button)showImage(button.dataset.shot)});
document.querySelectorAll('[data-evidence]').forEach(button=>button.addEventListener('click',()=>{const keys=button.dataset.evidence.split(',').filter(k=>images[k]);if(keys.length)openEvidence(keys[0],keys)}));
const picker=document.getElementById('section-picker');picker.addEventListener('change',()=>document.getElementById(picker.value).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));
const articles=[...document.querySelectorAll('main>article')];let queued=false;
function progress(){queued=false;const max=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--progress',(max>0?scrollY/max*100:0)+'%');let current=articles[0];for(const a of articles)if(a.getBoundingClientRect().top<=160)current=a;picker.value=current.id;document.querySelectorAll('.site-header nav a').forEach(a=>{if(a.hash==='#'+current.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
addEventListener('scroll',()=>{if(!queued){queued=true;requestAnimationFrame(progress)}},{passive:true});progress();
