(()=>{const section=document.getElementById('p09');if(!section)return;
const names=['Fatigue strength','Machine characteristics','Deformable solids'],rates=['49%','55.1%','55.1%'];const rows=[...section.querySelectorAll('[data-knowledge]')],recommendation=section.querySelector('.recommendation-panel');let selected=0;
function inspect(i){if(selected===i)return;selected=i;rows.forEach((row,n)=>row.setAttribute('aria-pressed',String(n===i)));section.querySelector('#knowledge-title').textContent=names[i];section.querySelector('#knowledge-observation').textContent=rates[i]+' score rate. Flagged as weak in the original product.';section.querySelector('#diagnosis-focus').textContent=names[i];}
rows.forEach((row,i)=>{row.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'){inspect(i);recommendation.classList.add('is-inspecting')}});row.addEventListener('pointerleave',()=>recommendation.classList.remove('is-inspecting'));row.addEventListener('focus',()=>{inspect(i);recommendation.classList.add('is-inspecting')});row.addEventListener('blur',()=>recommendation.classList.remove('is-inspecting'));row.addEventListener('click',()=>inspect(i));});
const buttons=[...section.querySelectorAll('[data-decision]')],editor=section.querySelector('#modify-response'),status=section.querySelector('#decision-status'),next=section.querySelector('#next-lesson-status');
buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));editor.hidden=button.dataset.decision!=='modify';if(button.dataset.decision==='accept'){status.textContent='Accepted for this demo lesson by the educator.';next.textContent='Next lesson: revisit the concept, add practice, then assess again.'}else if(button.dataset.decision==='ignore'){status.textContent='Recommendation ignored. No change is applied.';next.textContent='Next lesson: the existing plan stays in place; further assessment continues.'}else{status.textContent='Modify the response, then apply your decision to the demo.';next.textContent='The revised teaching response is awaiting educator confirmation.';section.querySelector('#teacher-response').focus()}}));
section.querySelector('#apply-response').addEventListener('click',()=>{const value=section.querySelector('#teacher-response').value.trim();if(!value){status.textContent='Add a teaching response before applying it.';section.querySelector('#teacher-response').focus();return}status.textContent='Your revised response is applied to this demo lesson.';next.textContent='Next lesson: '+value+' Further assessment follows.'});
if('IntersectionObserver'in window){section.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.15});section.querySelectorAll('.performance-panel,.reasoning-grid').forEach(el=>observer.observe(el));}
})();
